module.exports = {
  title: "H2O LLM Studio | Docs",
  tagline: "This code for this site was generated by Makersaurus",
  url: "https://docs.h2o.ai",
  baseUrl: "/h2o-llmstudio/",
  projectName: "h2o-llmstudio", // Usually your repo name
  feedbackAssignee: "sherenem", // Should be a github username
  feedbackLabels: ["llmstudio"],
  searchFilter: "h2o-llmstudio",
  showLastUpdateAuthor: false,
  includeCurrentVersion: true,
  versions: {
    current: {
      label: " ",
      path: "/",
    },
  },
  dependencies: {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@material-ui/core": "^4.12.4",
    "@material/card": "^14.0.0",
    "@mui/icons-material": "^5.10.16",
    "@mui/material": "^5.10.16",
    "react-player": "^2.11.0",
  },
};
