name: Build and Push Bundle to MC S3 - Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build_mc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LLM_STUDIO_AWS_ROLE }}
          role-session-name: ${{ secrets.LLM_STUDIO_AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.LLM_STUDIO_AWS_REGION }}
      - name: Build Wave Bundle
        run: |-
          make bundles
      - name: Push wave bundle to S3
        run: |-
          REF_NAME="${{ github.ref_name }}"
          VERSION=${REF_NAME:1}
          aws s3 cp bundles/ai.h2o.llmstudio.$VERSION.wave ${{ secrets.MC_S3_LLMSTUDIO_BUCKET }}.$VERSION.wave
  build_internal:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LLM_STUDIO_INTERNAL_AWS_ROLE }}
          role-session-name: ${{ secrets.LLM_STUDIO_INTERNAL_AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.LLM_STUDIO_INTERNAL_AWS_REGION }}
      - name: Build Wave Bundle
        run: |-
          make bundles
      - name: Docker Build Image
        run: |-
          REF_NAME="${{ github.ref_name }}"
          VERSION=${REF_NAME:1}
          docker build -t ${{ secrets.LLM_STUDIO_INTERNAL_AWS_ECR }}:${{ github.ref_name }}-bundle --build-arg VERSION=$VERSION -f Dockerfile.bundle .
      - name: Push to AWS
        run: |-
          docker push ${{ secrets.LLM_STUDIO_INTERNAL_AWS_ECR }}:${{ github.ref_name }}-bundle
