name: Build and Push to GAR - Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/135982812994/locations/global/workloadIdentityPools/cicd-tooling/providers/github-actions'
          service_account: 'artifact-rw@vorvan.iam.gserviceaccount.com'
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker ${{ secrets.GAR_REPOSITORY }} --quiet #authenticate to gar
      - name: Clean Docker images
        run: |-
          echo "Available storage before cleaning:"
          df -h
          docker system prune --all --force
          echo "Available storage:"
          df -h
          echo "Removing dotnet"
          sudo rm -rf /usr/share/dotnet
          echo "Available storage:"
          df -h
      - name: Docker Build Image
        run: |-
          docker build -t ${{ secrets.GAR_IMAGE_PATH }}:${{ github.ref_name }} . --quiet
      - name: Push to GAR
        run: |-
          docker push ${{ secrets.GAR_IMAGE_PATH }}:${{ github.ref_name }} --quiet
